#!/bin/bash
threshold=5 # Size in GB to alert on
alert() {
    emails=("jacquesaronius@gmail.com") # Email addresses to notify
    #for i in $emails
    #do
    echo "Docker container $1 is using more than $threshold GB"
}

cmd_out=`docker ps --format "{{ .Names }} {{ .Size }}" -a --size \
| grep -v MB | sed -E "s/GB.*//"`

SAVEIFS=$IFS
IFS=$'\n'
cmd_lines=($cmd_out)
for i in ${cmd_lines[@]}
do
    IFS=$' '
    fields=($i)
    IFS=$'\n'
    name=${fields[0]}
    size=${fields[1]}


    if ((`echo "$size > $threshold" | bc -l`))
    then 
        alert $name
    fi
done
IFS=$SAVEIFS